### PR TITLE
fix(import): allow `+` , `*` and `:` in enums

### LINKED ISSUE #267: Import fails for some enums
Some enums trip up the import (I'm guessing because it doesn't know how to sensibly give them a ts constant name). As an example I was trying to import https://github.com/rook/rook/blob/release-1.9/deploy/examples/crds.yaml, which has an enum:
```
enum:
- s3:ObjectCreated:*
- s3:ObjectCreated:Put
- s3:ObjectCreated:Post
- s3:ObjectCreated:Copy
- s3:ObjectCreated:CompleteMultipartUpload
- s3:ObjectRemoved:*
- s3:ObjectRemoved:Delete
- s3:ObjectRemoved:DeleteMarkerCreated
```
But cdk8s turns that into:
```
export enum CephBucketNotificationSpecEvents {
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
}
```
Which obviously fails to compile. I'm not sure how this should be handled generically though.

### LINKED ISSUE #578: Importing prometheus-operator CRD causes compile to fail
When importing `https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.60.1/bundle.yaml` the compile fails with following error

image

From imported CRD:

```
export enum AlertmanagerConfigSpecInhibitRulesSourceMatchMatchType {
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
}

/**
 * Match operation available with AlertManager >= v0.22.0 and takes precedence over Regex (deprecated) if non-empty.
 *
 * @schema AlertmanagerConfigSpecInhibitRulesTargetMatchMatchType
 */
export enum AlertmanagerConfigSpecInhibitRulesTargetMatchMatchType {
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
  /** __stripped_by_cdk8s__ */
  STRIPPED_BY_CDK8S = '__stripped_by_cdk8s__',
}
```

### LINKED ISSUE #1072: CDK8S Strips out enums with with colons in them
### Description of the bug:

When importing this CRD from Terraform [app.terraform.io_workspaces](https://github.com/hashicorp/terraform-cloud-operator/blob/main/charts/terraform-cloud-operator/crds/app.terraform.io_workspaces.yaml) CDK8S generates the following invalid Syntax for the NotificationTriggers

image

These enums are being stripped out because they contain a colon in them: 
image

First: enums with colons in them should be supported
Second: CDK8S should not be generating invalid Typescript by creating multiple entries for STRIPPED_BY_CDK8S

This issue can be referenced in a few other spots: 
[#229](https://github.com/cdk8s-team/cdk8s-cli/issues/229)
[#267](https://github.com/cdk8s-team/cdk8s-cli/issues/267)
[#578](https://github.com/cdk8s-team/cdk8s-cli/issues/578)

There was one bug fixed here: https://github.com/cdk8s-team/cdk8s-cli/pull/196 for spaces, but none the less it stil persists for other characters. 

### Reproduction Steps:

Import the terraform workspace crd and generate

### Error Log:

Duplicate identifier 'STRIPPED_BY_CDK8S'

### Environment:

  - **Framework Version**:  2.2.90
  - **OS**: OSX

### Other:

---

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by rassie**
During an import, `cdk8s-cli` checks for certain characters in `enum`s  and replaces values perceived as invalid with `STRIPPED_BY_CDK8S`. This fails for multiple CRDs in the wild which contain `+` and `:` in `enum` value. This PR fixes that. Generated code looks fine from my POV. 

Fixes #1072
Fixes #267

### CODE REVIEW

**Comment by rassie** [comment]
If we add `*`, we'll solve #267 as well, seems like low-hanging fruit. Should I just add it?

**Comment by iliapolo** [comment]
@rassie Thanks for this! 

Regarding https://github.com/cdk8s-team/cdk8s-cli/issues/267 - yes lets add the `*` as well 👍 

Regarding https://github.com/cdk8s-team/cdk8s-cli/issues/1072 - I think we can mark it as to be resolved as well because the `STRIPPED_BY_CDK8S` part is a different issue that I will split out.

Regarding https://github.com/cdk8s-team/cdk8s-cli/issues/578 - you mention it resolves it, but that issue speaks about enum values like: `!=, =, =~, !~` - which this PR doesn't seem to address. Right? Its actually a duplicate of https://github.com/cdk8s-team/cdk8s-cli/issues/229

**Comment by rassie** [comment]
> Regarding #578 - you mention it resolves it, but that issue speaks about enum values like: `!=, =, =~, !~` - which this PR doesn't seem to address. Right? Its actually a duplicate of #229

Yes, I think you are correct, even though #578 doesn't talk explicitely about comparison operators, they are in the YAML definition. They are also a bit more difficult to fix (need a replacement like `EQUALS` for `=` etc.), so I'd leave them be for now.

**Comment by rassie** [comment]
@iliapolo I think that should do it. Forgot to update the snapshots first, is fixed now.

**Review by iliapolo — APPROVED** [review]

**Pull request merged**
